apiVersion: v1
kind: Service
metadata:
  name: python-web-service
  namespace: web-tech-challenge-saurabhyeolekar
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 3030
    targetPort: 3035
  selector:
    name: fibo-python-web-app