apiVersion: v1
kind: Service
metadata:
  name: go-web-service
  namespace: web-tech-challenge-saurabhyeolekar
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 3030
    targetPort: 3000
  selector:
    name: fibo-go-web-app